### ISSUE TITLE
Discogs handler returns "Error: makeHandlerFactory doesn't suport OAuth 1 yet"

### ISSUE THREAD

**Issue by kilinkis** [fiberinc/handshake#43]
**Describe the bug**
After following the docs, I get this error using the Discogs handler:

```
Discogs handler returns "Error: makeHandlerFactory doesn't suport OAuth 1 yet"
```

**To Reproduce**

1. clone repo
2. add discog credentials and snippet from the docs
3. add login button in the ui and click it

**Expected behavior**
login should work

**Comment by felipap** [comment]
@kilinkis I think we got it. Check out #44 if you can. 👋
